kind: pipeline
type: docker
name: publish

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: cluster.gov:5000/streambot
      tags:
        - latest
      registry: cluster.gov:5000
      insecure: true
