version: '3.9'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/code
    depends_on:
      - cache

  worker:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/code
    command: poetry run watchmedo auto-restart --patterns="*.py" --recursive -- poetry run celery -A streambot.celery worker --loglevel=INFO -P processes
    depends_on:
      - cache

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/code
    command: poetry run watchmedo auto-restart --patterns="*.py" --recursive -- poetry run celery -A streambot.celery beat --loglevel=INFO
    depends_on:
      - cache

  cache:
    image: redis:latest
